### ISSUE TITLE
添加CPU 频率和温度信息后，Safari 无法打开 webui

### ISSUE THREAD

**Issue by dcty** [iKoolCore/PVE_Status_Tools#1]
OS: Proxmox VE 7.2-11 x86_64
Kernel: 5.15.60-2-pve
1、执行命令：wget -qO-  https://raw.githubusercontent.com/iKoolCore/PVE_Status_Tools/main/PVE_Status_Tools.sh | bash
2、Safari 新建无痕窗口，访问 pve 的 webui ，一片空白，打开网页检查器，发现有一行报错,如下图所示。
<img width="813" alt="image" src="https://user-images.githubusercontent.com/792929/195993156-e71a1813-504a-4813-8adb-71d91354a651.png">

**Comment by AuroraWatt** [comment]
**没测试过Safari下的兼容性。建议使用chrome。Chrome下我这边暂时没发现问题**
